name: Publish Python Package

on:
  release:
    tags:
      - 'v*'  # Trigger on tagged commits (e.g., v1.0, v2.0)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          # Install your package's build dependencies
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
